### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by heyjones** [zype/zype-wordpress-plugin#31]
When I try to activate the plugin I get the following error:

```PHP Fatal error: Uncaught GuzzleHttp\\Exception\\RequestException: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /wp-content/plugins/zype-wordpress-plugin-0.9.5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186\nStack trace:\n#0 /wp-content/plugins/zype-wordpress-plugin-0.9.5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)\n#1 /wp-content/plugins/zype-wordpress-plugin-0.9.5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#2 /wp-content/plugins/zype-wordpress-plugin-0.9.5/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), in /wp-content/plugins/zype-wordpress-plugin-0.9.5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186, referer: /wp-admin/plugins.php?plugin_status=all&paged=1&s```

**Comment by heyjones** [comment]
I just tried it again and it activated, not sure what the problem was earlier.
